/**
 * Generates src/client/practice/preflopTable.ts: the equity of each of the 169 starting-hand classes against
 * 1 to 5 random hands, by Monte Carlo with the game's own evaluator. Run with:
 *   npx esbuild scripts/preflop-table.ts --bundle --platform=node --format=esm --outfile=/tmp/preflop.mjs && node /tmp/preflop.mjs
 * from the repository root.
 */
import { writeFileSync } from "node:fs";
import { handScore } from "../src/engine/evaluator";
import { seededRng } from "../src/engine/rng";
import { RANKS, SUITS, type Card } from "../src/shared/cards";

const ITERATIONS = Number(process.env.ITER ?? 20000);
const rng = seededRng(20260929);
const deck: Card[] = RANKS.flatMap((r) => SUITS.map((s) => `${r}${s}` as Card));

/** Classes in the usual grid order: pairs, then suited and offsuit combos, high card first. */
function classes(): { name: string; cards: [Card, Card] }[] {
  const out: { name: string; cards: [Card, Card] }[] = [];
  const R = [...RANKS].reverse();
  for (let i = 0; i < R.length; i++) {
    for (let j = i; j < R.length; j++) {
      if (i === j) out.push({ name: R[i] + R[j], cards: [`${R[i]}s` as Card, `${R[j]}h` as Card] });
      else {
        out.push({ name: R[i] + R[j] + "s", cards: [`${R[i]}s` as Card, `${R[j]}s` as Card] });
        out.push({ name: R[i] + R[j] + "o", cards: [`${R[i]}s` as Card, `${R[j]}h` as Card] });
      }
    }
  }
  return out;
}

function equity(hole: [Card, Card], opponents: number): number {
  const rest = deck.filter((c) => c !== hole[0] && c !== hole[1]);
  let share = 0;
  const need = opponents * 2 + 5;
  for (let it = 0; it < ITERATIONS; it++) {
    // Partial Fisher-Yates: only the cards we need.
    for (let k = 0; k < need; k++) {
      const j = k + rng.int(rest.length - k);
      [rest[k], rest[j]] = [rest[j], rest[k]];
    }
    const board = rest.slice(opponents * 2, need);
    const mine = handScore([...hole, ...board]);
    let best = true;
    let ties = 1;
    for (let o = 0; o < opponents; o++) {
      const s = handScore([rest[o * 2], rest[o * 2 + 1], ...board]);
      if (s > mine) {
        best = false;
        break;
      }
      if (s === mine) ties++;
    }
    if (best) share += 1 / ties;
  }
  return share / ITERATIONS;
}

const list = classes();
const rows: string[] = [];
for (const c of list) {
  const eqs = [1, 2, 3, 4, 5].map((n) => Math.round(equity(c.cards, n) * 1000));
  rows.push(`  "${c.name}": [${eqs.join(", ")}],`);
}
const src = `// Generated by scripts/preflop-table.ts. Do not edit by hand.
/** Equity (per mille) of each starting-hand class against 1 to 5 random hands. */
export const PREFLOP_EQUITY: Record<string, readonly [number, number, number, number, number]> = {
${rows.join("\n")}
};
`;
writeFileSync("src/client/practice/preflopTable.ts", src);
console.log(`wrote ${list.length} classes`);
